language: objective-c
osx_image: xcode9.3
branches:
  only:
    - develop
    - master
env:
  - DESTINATION="OS=11.3,name=iPhone 8" SCHEME="PodoCalendarExample" SDK=iphonesimulator

before_install:
- gem install cocoapods -v '1.5.3'
- pod install --repo-update
script:
- set -o pipefail
- travis_retry xcodebuild -workspace PodoCalendar.xcworkspace -scheme "$SCHEME" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
