language: objective-c
osx_image: xcode9.3
branches:
  only:
    - develop
    - master
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods -v '1.5.3'
- pod install --repo-update --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Example.xcworkspace -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
